/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadways_project;


import com.sun.webkit.dom.EventImpl;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyListener;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author Ekam
 */
public class login extends javax.swing.JFrame implements mycred,KeyListener{

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Ekam\\Documents\\NetBeansProjects\\Roadways_Project\\build\\classes\\Images\\Bus-icon.png"));
        //jPasswordField1.addKeyListener(this);
        //this.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Password");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 70, 530, 352);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ekam\\Documents\\NetBeansProjects\\Roadways_Project\\prj-Images\\bkgd.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 530);

        setSize(new java.awt.Dimension(760, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


  try
        {
            Connection mycon= DriverManager.getConnection(path+place,uname,pass);
            try
            {
                String q="select * from admintable where username=? and password = ?";
                PreparedStatement mstate= mycon.prepareStatement(q);
                mstate.setString(1,jTextField1.getText());
                mstate.setString(2,jPasswordField1.getText());
                ResultSet myresult = mstate.executeQuery();
                
                if(myresult.next())
                {
                   MyMain.cuser = jTextField1.getText();
                   admin_form obj= new admin_form();
                   obj.setVisible(true);
                   this.dispose();
                }
                else
                {
                    String q2="select * from employeetable where username=? and password = ?";
                    
                    PreparedStatement mstate2= mycon.prepareStatement(q2);
                    mstate2.setString(1,jTextField1.getText());
                    mstate2.setString(2,jPasswordField1.getText());
                    ResultSet myresult2 = mstate2.executeQuery();

                    if(myresult2.next())
                    {
                       MyMain.cuser = jTextField1.getText();
                       employee_form obj= new employee_form();
                       obj.setVisible(true);
                       this.dispose();
                    }
                    else
                    {
                       JOptionPane.showMessageDialog(rootPane," Invalid username / password ");
                    }
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error Updating Query : "+e.getMessage());
            }
            finally
            {
                mycon.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in connection "+e.getMessage());
        }
            }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed

        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try
            {
                Connection mycon= DriverManager.getConnection(path+place,uname,pass);
                try
                {
                    String q="select * from admintable where username=? and password = ?";
                    PreparedStatement mstate= mycon.prepareStatement(q);
                    mstate.setString(1,jTextField1.getText());
                    mstate.setString(2,jPasswordField1.getText());
                    ResultSet myresult = mstate.executeQuery();

                    if(myresult.next())
                    {
                       MyMain.cuser = jTextField1.getText();
                       admin_form obj= new admin_form();
                       obj.setVisible(true);
                       this.dispose();
                    }
                    else
                    {
                        String q2="select * from employeetable where username=? and password = ?";

                        PreparedStatement mstate2= mycon.prepareStatement(q2);
                        mstate2.setString(1,jTextField1.getText());
                        mstate2.setString(2,jPasswordField1.getText());
                        ResultSet myresult2 = mstate2.executeQuery();

                        if(myresult2.next())
                        {
                           MyMain.cuser = jTextField1.getText();
                           employee_form obj= new employee_form();
                           obj.setVisible(true);
                           this.dispose();
                        }
                        else
                        {
                           JOptionPane.showMessageDialog(rootPane," Invalid username / password ");
                        }
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error Updating Query : "+e.getMessage());
                }
                finally
                {
                    mycon.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in connection "+e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        
    }//GEN-LAST:event_formKeyPressed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        
    }//GEN-LAST:event_jPasswordField1KeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    
    }
//    @Override
//    public void keyPressed(KeyEvent k)
//    {
//        if(k.getKeyCode()==KeyEvent.VK_E)
//        {
//            try
//        {
//            Connection mycon= DriverManager.getConnection(path+place,uname,pass);
//            try
//            {
//                String q="select * from admintable where username=? and password = ?";
//                PreparedStatement mstate= mycon.prepareStatement(q);
//                mstate.setString(1,jTextField1.getText());
//                mstate.setString(2,jPasswordField1.getText());
//                ResultSet myresult = mstate.executeQuery();
//                
//                if(myresult.next())
//                {
//                   MyMain.cuser = jTextField1.getText();
//                   admin_form obj= new admin_form();
//                   obj.setVisible(true);
//                   this.dispose();
//                }
//                else
//                {
//                    String q2="select * from employeetable where username=? and password = ?";
//                    
//                    PreparedStatement mstate2= mycon.prepareStatement(q2);
//                    mstate2.setString(1,jTextField1.getText());
//                    mstate2.setString(2,jPasswordField1.getText());
//                    ResultSet myresult2 = mstate2.executeQuery();
//
//                    if(myresult2.next())
//                    {
//                       MyMain.cuser = jTextField1.getText();
//                       employee_form obj= new employee_form();
//                       obj.setVisible(true);
//                       this.dispose();
//                    }
//                    else
//                    {
//                       JOptionPane.showMessageDialog(rootPane," Invalid username / password ");
//                    }
//                }
//            }
//            catch(Exception e)
//            {
//                JOptionPane.showMessageDialog(rootPane,"Error Updating Query : "+e.getMessage());
//            }
//            finally
//            {
//                mycon.close();
//            }
//        }
//        catch(Exception e)
//        {
//            JOptionPane.showMessageDialog(rootPane,"Error in connection "+e.getMessage());
//        }
//            
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}