/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadways_project;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Ekam
 */
public class remDepar extends javax.swing.JInternalFrame implements mycred{

    /**
     * Creates new form remDepar
     */
    public remDepar() {
        initComponents();
        jComboBox1.addItem("Choose City");
        try
        {
            Connection mycon = DriverManager.getConnection(path+place,uname,pass);
            try
            {
                String q = "select * from startdb  ";
                PreparedStatement mystate = mycon.prepareStatement(q);
                
                ResultSet myres = mystate.executeQuery();
                if(myres.next())
                {
                    do
                    {
                        jComboBox1.addItem(myres.getString("scity"));
                    }
                    while(myres.next());
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query "+e.getMessage());
                
            }
            
          
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in Connection "+e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int res = JOptionPane.showConfirmDialog(rootPane,"Do you Really want to remove city","Confirm",JOptionPane.YES_NO_OPTION);
        
        if(res==JOptionPane.YES_OPTION)
        {
            try
            {
                Connection mycon = DriverManager.getConnection(path+place,uname,pass);


                try
                {
                    String q = "delete from startdb where scity=? ";
                    PreparedStatement mystate = mycon.prepareStatement(q);
                    mystate.setString(1,jComboBox1.getSelectedItem().toString());
                    
                    int exe = mystate.executeUpdate();
                    if(exe>0)
                    {
                        JOptionPane.showMessageDialog(rootPane,"City Removed");
                        jComboBox1.removeAllItems();
                        jComboBox1.addItem("Choose City");
                        
                        try
                        {
                            Connection mycon2 = DriverManager.getConnection(path+place,uname,pass);
                            try
                            {
                                String q2 = "select * from startdb  ";
                                PreparedStatement mystate2 = mycon2.prepareStatement(q2);

                                ResultSet myres2 = mystate2.executeQuery();
                                if(myres2.next())
                                {
                                    do
                                    {
                                        jComboBox1.addItem(myres2.getString("scity"));
                                    }
                                    while(myres2.next());
                                }

                            }
                            catch(Exception e)
                            {
                                JOptionPane.showMessageDialog(rootPane,"Error in Query : "+e.getMessage());

                            }
                        }
                        catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(rootPane,"Error in Connection : "+e.getMessage());
                        }
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in Query "+e.getMessage());
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Connection "+e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
