/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu;

/**
 *
 * @author Ekam
 */
public class quiz2 extends javax.swing.JFrame {

    /**
     * Creates new form quiz
     */
    public quiz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jScrollBar1);
        jScrollBar1.setBounds(1138, 0, 30, 863);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quiz no");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(388, 57, 232, 56);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Question 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(61, 147, 147, 48);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 131, 748, 96);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(220, 267, 107, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton1");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(432, 267, 107, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton1");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(645, 267, 107, 25);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton1");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(861, 267, 107, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Question 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(61, 428, 147, 48);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 412, 748, 96);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("jRadioButton1");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(220, 548, 107, 25);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("jRadioButton1");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(432, 548, 107, 25);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("jRadioButton1");
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(645, 548, 107, 25);

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("jRadioButton1");
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(861, 548, 107, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Question 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 705, 147, 48);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(220, 693, 748, 96);

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("jRadioButton1");
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(220, 829, 107, 25);

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText("jRadioButton1");
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(432, 829, 107, 25);

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setText("jRadioButton1");
        getContentPane().add(jRadioButton11);
        jRadioButton11.setBounds(645, 829, 107, 25);

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setText("jRadioButton1");
        getContentPane().add(jRadioButton12);
        jRadioButton12.setBounds(861, 829, 107, 25);
        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(70, 0, 1100, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
